<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO5cYCIx\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO5cYCIx/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO5cYCIx.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO5cYCIx\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO5cYCIx\App_KernelDevDebugContainer([
    'container.build_hash' => 'O5cYCIx',
    'container.build_id' => 'f5bb2702',
    'container.build_time' => 1751401082,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO5cYCIx');
