<?php

namespace ContainerO5cYCIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AP1Jq7jService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aP1Jq7j' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aP1Jq7j'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CheckoutController::checkout' => ['privates', '.service_locator.G8pW2xR.App\\Controller\\CheckoutController::checkout()', 'getCheckoutControllercheckoutService', true],
            'App\\Controller\\OrderController::placeOrder' => ['privates', '.service_locator.aA4SkN_.App\\Controller\\OrderController::placeOrder()', 'getOrderControllerplaceOrderService', true],
            'App\\Controller\\RegistrationController::index' => ['privates', '.service_locator.CYxM78o.App\\Controller\\RegistrationController::index()', 'getRegistrationControllerindexService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\ViewProductController::piece' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ViewProductController::piece()', 'getViewProductControllerpieceService', true],
            'App\\Controller\\ViewProductController::index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ViewProductController::index()', 'getViewProductControllerindexService', true],
            'App\\Controller\\ViewProductController::showProductsByCategory' => ['privates', '.service_locator.nrD4V8q.App\\Controller\\ViewProductController::showProductsByCategory()', 'getViewProductControllershowProductsByCategoryService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.zHyJIs5.kernel::registerContainerConfiguration()', 'get_ServiceLocator_ZHyJIs5_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.zHyJIs5.kernel::loadRoutes()', 'get_ServiceLocator_ZHyJIs5_KernelloadRoutesService', true],
            'App\\Controller\\CheckoutController:checkout' => ['privates', '.service_locator.G8pW2xR.App\\Controller\\CheckoutController::checkout()', 'getCheckoutControllercheckoutService', true],
            'App\\Controller\\OrderController:placeOrder' => ['privates', '.service_locator.aA4SkN_.App\\Controller\\OrderController::placeOrder()', 'getOrderControllerplaceOrderService', true],
            'App\\Controller\\RegistrationController:index' => ['privates', '.service_locator.CYxM78o.App\\Controller\\RegistrationController::index()', 'getRegistrationControllerindexService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.3QECKYg.App\\Controller\\SecurityController::login()', 'getSecurityControllerloginService', true],
            'App\\Controller\\ViewProductController:piece' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ViewProductController::piece()', 'getViewProductControllerpieceService', true],
            'App\\Controller\\ViewProductController:index' => ['privates', '.service_locator.vCPEyuw.App\\Controller\\ViewProductController::index()', 'getViewProductControllerindexService', true],
            'App\\Controller\\ViewProductController:showProductsByCategory' => ['privates', '.service_locator.nrD4V8q.App\\Controller\\ViewProductController::showProductsByCategory()', 'getViewProductControllershowProductsByCategoryService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\CheckoutController::checkout' => '?',
            'App\\Controller\\OrderController::placeOrder' => '?',
            'App\\Controller\\RegistrationController::index' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'App\\Controller\\ViewProductController::piece' => '?',
            'App\\Controller\\ViewProductController::index' => '?',
            'App\\Controller\\ViewProductController::showProductsByCategory' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\CheckoutController:checkout' => '?',
            'App\\Controller\\OrderController:placeOrder' => '?',
            'App\\Controller\\RegistrationController:index' => '?',
            'App\\Controller\\SecurityController:login' => '?',
            'App\\Controller\\ViewProductController:piece' => '?',
            'App\\Controller\\ViewProductController:index' => '?',
            'App\\Controller\\ViewProductController:showProductsByCategory' => '?',
        ]);
    }
}
