<?php

namespace ContainerO5cYCIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getCheckoutControllercheckoutService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G8pW2xR.App\Controller\CheckoutController::checkout()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G8pW2xR.App\\Controller\\CheckoutController::checkout()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
        ], [
            'passwordHasher' => '?',
            'doctrine' => '?',
        ]))->withContext('App\\Controller\\CheckoutController::checkout()', $container);
    }
}
