<?php

namespace ContainerO5cYCIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderControllerplaceOrderService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.aA4SkN_.App\Controller\OrderController::placeOrder()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.aA4SkN_.App\\Controller\\OrderController::placeOrder()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ur' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'ur' => 'App\\Repository\\UsersRepository',
        ]))->withContext('App\\Controller\\OrderController::placeOrder()', $container);
    }
}
