<?php

namespace ContainerO5cYCIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegistrationControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.CYxM78o.App\Controller\RegistrationController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.CYxM78o.App\\Controller\\RegistrationController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'UR' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
            'passwordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
        ], [
            'UR' => 'App\\Repository\\UsersRepository',
            'passwordHasher' => '?',
        ]))->withContext('App\\Controller\\RegistrationController::index()', $container);
    }
}
