<?php

namespace ContainerO5cYCIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewProductControllerpieceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vCPEyuw.App\Controller\ViewProductController::piece()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vCPEyuw.App\\Controller\\ViewProductController::piece()'] = ($container->privates['.service_locator.vCPEyuw'] ?? $container->load('get_ServiceLocator_VCPEyuwService'))->withContext('App\\Controller\\ViewProductController::piece()', $container);
    }
}
