<?php

namespace ContainerO5cYCIx;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getViewProductControllershowProductsByCategoryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nrD4V8q.App\Controller\ViewProductController::showProductsByCategory()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nrD4V8q.App\\Controller\\ViewProductController::showProductsByCategory()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'productRepository' => ['privates', 'App\\Repository\\ProductRepository', 'getProductRepositoryService', true],
            'paginator' => ['services', 'knp_paginator', 'getKnpPaginatorService', true],
        ], [
            'productRepository' => 'App\\Repository\\ProductRepository',
            'paginator' => '?',
        ]))->withContext('App\\Controller\\ViewProductController::showProductsByCategory()', $container);
    }
}
